name = "Queerpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e467ec1901f9f817fdb70fec20db5ca45d54ce71cb97b2729dabb85cb81957d"

[versions]
fabric = "0.8.9+build.203"
minecraft = "1.16.1"
yarn = "1.16.1+build.21"
