name = "Adabranium"
filename = "adabraniummod-2.1.1+1.17.1.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3378/780/adabraniummod-2.1.1%2B1.17.1.jar"
hash-format = "sha256"
hash = "2f67c38426fb5a5cab2e867412697915cb46e8be0252f3afab7806fc7fe2c931"

[update]
[update.curseforge]
file-id = 3294199
project-id = 361599
release-channel = "release"
