name = "Adorn"
filename = "Adorn-1.9.1+1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2990/980/Adorn-1.9.1+1.16.1.jar"
hash-format = "murmur2"
hash = "2965144539"

[update]
[update.curseforge]
file-id = 2990980
project-id = 320215
release-channel = "beta"
