name = "Architectury"
filename = "architectury-2.1.20-fabric.jar"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3376/69/architectury-2.1.20-fabric.jar"
hash-format = "sha256"
hash = "e21f8fa7c089ac94f192621199199345c45a32eda089f4b5ab694d3d1c52576b"
