name = "Beacon Overhaul"
filename = "BeaconOverhaul-1.4.1+1.17.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3380/414/BeaconOverhaul-1.4.1%2B1.17.jar"
hash-format = "sha256"
hash = "3bd41bbd71c8712cbb36ed43ed6dc03dcf2f4e4393af74b381f12f3aca043d39"

[update]
[update.curseforge]
file-id = 3212299
project-id = 430382
release-channel = "release"
