name = "Blockus"
filename = "blockus-2.0.2+20w51a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/302/blockus-2.0.2+20w51a.jar"
hash-format = "murmur2"
hash = "1823623803"

[update]
[update.curseforge]
file-id = 3143302
project-id = 312289
release-channel = "beta"
