name = "Blockus"
filename = "blockus-2.2.6+1.17.1.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3381/862/blockus-2.2.6%2B1.17.1.jar"
hash-format = "sha256"
hash = "157c1ea45de40e67ab9cc0d7fd280ea36c5870cdefa354cc5867479669740448"

[update]
[update.curseforge]
file-id = 3328104
project-id = 312289
release-channel = "release"
