name = "Blur (Fabric)"
filename = "Blur-1.0.6-1.16.1.fabric.jar"
side = "client"

[option]
optional = true
description = "Adds a blur effect to all GUI backgrounds"
default = false

[download]
url = "https://edge.forgecdn.net/files/2996/212/Blur-1.0.6-1.16.1.fabric.jar"
hash-format = "murmur2"
hash = "3909396910"

[update]
[update.curseforge]
file-id = 2996212
project-id = 393563
release-channel = "beta"
