name = "BoatFix"
filename = "boatfix-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/975/boatfix-1.0.0.jar"
hash-format = "murmur2"
hash = "3585699199"

[update]
[update.curseforge]
file-id = 2988975
project-id = 392013
release-channel = "beta"
