name = "Cauldron"
filename = "cauldrons-1.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/d94jcdPG/versions/1.1.1/cauldrons-1.1.1.jar"
hash-format = "sha256"
hash = "cb3b82122f9b8994988a6179232646a90344353d345d47e08026c2e3badc0e15"
