name = "Cinderscapes"
filename = "cinderscapes-1.0.4+build.25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2995/636/cinderscapes-1.0.4+build.25.jar"
hash-format = "murmur2"
hash = "1860221448"

[update]
[update.curseforge]
file-id = 2995636
project-id = 391429
release-channel = "beta"
