name = "ClickThrough"
filename = "clickthrough-20w49a-fabric0.27.2-0.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Z5b0cAlD/versions/20w49a-fabric0.27.2-0.3/clickthrough-20w49a-fabric0.27.2-0.3.jar"
hash-format = "sha256"
hash = "f5841728aaedb3a7fcae374b4bfb6f716f86e4528d1d4d27f685e72045419e0a"
