name = "Cloth Config API (Fabric)"
filename = "config-2-4.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3004/708/config-2-4.6.0.jar"
hash-format = "murmur2"
hash = "2519192840"

[update]
[update.curseforge]
file-id = 3004708
project-id = 319057
release-channel = "beta"
