name = "Columns"
filename = "columns-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3000/352/columns-1.1.0.jar"
hash-format = "murmur2"
hash = "769327856"

[update]
[update.curseforge]
file-id = 3000352
project-id = 385230
release-channel = "beta"
