name = "Door(s) Coupling [FABRIC]"
filename = "Couplings-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3004/726/Couplings-1.3.1.jar"
hash-format = "murmur2"
hash = "3656129882"

[update]
[update.curseforge]
file-id = 3004726
project-id = 395659
release-channel = "beta"
