name = "Crowmap"
filename = "crowmap+1.16.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2990/12/crowmap+1.16.1-1.0.1.jar"
hash-format = "murmur2"
hash = "29585999"

[update]
[update.curseforge]
file-id = 2990012
project-id = 301943
release-channel = "beta"
