name = "Don't Drop It!"
filename = "dontdropit-1.2.2+1.16.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3011/483/dontdropit-1.2.2+1.16.jar"
hash-format = "murmur2"
hash = "2516832852"

[update]
[update.curseforge]
file-id = 3011483
project-id = 390383
release-channel = "beta"

[option]
optional = true
description = "Prevents accidental dropping of items via various means."
