name = "Duyguji"
filename = "duyguji-client-base-0.3.0+1.16.1.jar"
side = "client"

[option]
optional = false
description = "The fabric mod for all your emoji needs 😂👌💯💦"
default = false

[download]
url = "https://github.com/Sturmlilie/duyguji-client-base/releases/download/v0.3.0/duyguji-client-base-0.3.0+1.16.1.jar"
hash-format = "sha256"
hash = "abaafcbbd23e67178d57b758903c9212f1e247da73f02713ee15412facdcce74"
