name = "Duyguji"
filename = "duyguji-client-font-0.1.1+1.16.1.jar"
side = "client"

[option]
optional = false
description = "The fabric mod for all your emoji needs 😂👌💯💦"
default = false

[download]
url = "https://github.com/Sturmlilie/duyguji-client-font/releases/download/v0.1.1/duyguji-client-font-0.1.1+1.16.1.jar"
hash-format = "sha256"
hash = "45d8f4715c33e3c7f5027d55a673a1d50a7c8998e59540a12fb9e3965195a95e"
