name = "Duyguji"
filename = "duyguji-client-input-0.4.0+1.16.1.jar"
side = "client"

[option]
optional = false
description = "The fabric mod for all your emoji needs 😂👌💯💦"
default = false

[download]
url = "https://github.com/Sturmlilie/duyguji-client-input/releases/download/v0.4.0/duyguji-client-input-0.4.0+1.16.1.jar"
hash-format = "sha256"
hash = "26a760108db5ed484b0cdf90033e8248649ac58f9b17b4001e070dcb53820cfa"
