name = "Environmental Creepers"
filename = "environmentalcreepers-forge-1.16.1-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3011/121/environmentalcreepers-forge-1.16.1-1.6.1.jar"
hash-format = "murmur2"
hash = "3667778296"

[update]
[update.curseforge]
file-id = 3011121
project-id = 246320
release-channel = "beta"
