name = "[Fabric] Expanded Storage"
filename = "expandedstorage-6.0.1+20w46a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3108/888/expandedstorage-6.0.1+20w46a.jar"
hash-format = "murmur2"
hash = "837220874"

[update]
[update.curseforge]
file-id = 3108888
project-id = 317856
release-channel = "beta"
