name = "Fabric API"
filename = "fabric-api-0.27.2+1.17.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3128/680/fabric-api-0.27.2+1.17.jar"
hash-format = "murmur2"
hash = "1391915933"

[update]
[update.curseforge]
file-id = 3128680
project-id = 306612
release-channel = "beta"
