name = "Fabric API"
filename = "fabric-api-0.28.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3136/849/fabric-api-0.28.1+1.17.jar"
hash-format = "murmur2"
hash = "3587956713"

[update]
[update.curseforge]
file-id = 3136849
project-id = 306612
release-channel = "beta"
