name = "Fabric API"
filename = "fabric-api-0.14.1+build.372-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2993/273/fabric-api-0.14.1+build.372-1.16.jar"
hash-format = "murmur2"
hash = "2974115558"

[update]
[update.curseforge]
file-id = 2993273
project-id = 306612
release-channel = "beta"
