name = "Fabric API"
filename = "fabric-api-0.26.4+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3123/122/fabric-api-0.26.4+1.17.jar"
hash-format = "murmur2"
hash = "1655733889"

[update]
[update.curseforge]
file-id = 3123122
project-id = 306612
release-channel = "beta"
