name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.3.72+build.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/695/fabric-language-kotlin-1.3.72+build.1.jar"
hash-format = "murmur2"
hash = "1586467111"

[update]
[update.curseforge]
file-id = 2989695
project-id = 308769
release-channel = "beta"
