name = "Fabric API"
filename = "fabric-api-0.16.0+build.384-1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3013/647/fabric-api-0.16.0+build.384-1.16.1.jar"
hash-format = "murmur2"
hash = "3210425253"

[update]
[update.curseforge]
file-id = 3013647
project-id = 306612
release-channel = "beta"
