name = "Fabric API"
filename = "fabric-api-0.29.5+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3175/287/fabric-api-0.29.5+1.17.jar"
hash-format = "murmur2"
hash = "3350371188"

[update]
[update.curseforge]
file-id = 3175287
project-id = 306612
release-channel = "beta"
