name = "Go Down !"
filename = "godown-0.2.0+1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2993/713/godown-0.2.0+1.16.1.jar"
hash-format = "murmur2"
hash = "604867946"

[update]
[update.curseforge]
file-id = 2993713
project-id = 360899
release-channel = "beta"
