name = "Gravestones"
filename = "gravestones-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2998/195/gravestones-1.4.0.jar"
hash-format = "murmur2"
hash = "2863400752"

[update]
[update.curseforge]
file-id = 2998195
project-id = 373595
release-channel = "beta"
