name = "Illuminations"
filename = "illuminations-1.6.jar"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3385/132/illuminations-1.6.jar"
hash-format = "sha256"
hash = "68074b3665842656b32aec7eba679d2c9fd37470abe4cc668c9e0c47189a662b"
