name = "Illuminations"
filename = "illuminations-1.5.2.jar"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3381/387/illuminations-1.5.2.jar"
hash-format = "sha256"
hash = "5eb65d90283ed1dea751d330e259ad5795dc554ee85c6976da5393e91c2b1987"
