name = "Inventory Sorting"
filename = "InventorySorter-1.6.7-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/315/InventorySorter-1.6.7-1.16.jar"
hash-format = "murmur2"
hash = "1093967336"

[update]
[update.curseforge]
file-id = 2987315
project-id = 325471
release-channel = "beta"
