name = "Inventory Profiles"
filename = "inventoryprofiles-fabric-1.16.1-0.4.2.jar"
side = "both"

[option]
optional = true
description = "Inventory and container sorting, equipment profiles switching, bunch of combat/building tweaks, etc."
default = true

[download]
url = "https://edge.forgecdn.net/files/3005/22/inventoryprofiles-fabric-1.16.1-0.4.2.jar"
hash-format = "murmur2"
hash = "440351803"

[update]
[update.curseforge]
file-id = 3005022
project-id = 347463
release-channel = "beta"
