name = "Iron Bundles"
filename = "ironbundles-1.0.1+20w49a.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GrvAgLaJ/versions/1.0.1+20w49a/ironbundles-1.0.1+20w49a.jar"
hash-format = "sha256"
hash = "858906099305b6527c4f18eafc9284a2d37e39f374a6fb733ae2fcd9caf48205"
