name = "LambDynamicLights"
filename = "lambdynamiclights-fabric-1.2.1+1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3000/619/lambdynamiclights-fabric-1.2.1+1.16.1.jar"
hash-format = "murmur2"
hash = "1296327048"

[update]
[update.curseforge]
file-id = 3000619
project-id = 393442
release-channel = "beta"
