name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-5.4.1.jar"
side = "client"

[option]
optional = true
description = "A simple mod to provide users with NEI-like light level overlay."
default = false

[download]
url = "https://edge.forgecdn.net/files/3005/495/light-overlay-5.4.1.jar"
hash-format = "murmur2"
hash = "779288692"

[update]
[update.curseforge]
file-id = 3005495
project-id = 325492
release-channel = "beta"
