name = "Litematica"
filename = "litematica-fabric-1.17-snap-21w05a-0.0.0-dev.20210204.184419.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/Queerbric/queerpack/1.17/mods/litematica-fabric-1.17-snap-21w05a-0.0.0-dev.20210204.184419.jar"
hash-format = "sha256"
hash = "cdb5768cae8d85c8f6a518e1b3d1ebf6b51afaebdb1a7072d48cb8228d7f028c"

[option]
optional = true
