name = "MaLiLib"
filename = "malilib-fabric-1.17.1-0.10.0-dev.24.jar"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3387/61/malilib-fabric-1.17.1-0.10.0-dev.24.jar"
hash-format = "sha256"
hash = "0b0ae86c9e39b7b3bedfe41a85eb7f330d3d1fc8afcda4b74f60f236ef6ee4dd"
