name = "MaLiLib"
filename = "malilib-fabric-1.17-snap-20w49a-0.10.0-dev.21+beta.1.jar"
side "client"

[download]
url = "https://raw.githubusercontent.com/Queerbric/queerpack/1.17/mods/malilib-fabric-1.17-snap-20w49a-0.10.0-dev.21+beta.1.jar"
hash-format = "sha256"
hash = "f0153ead4d7e25900b48048f62bef596717039ea4d16ffbbb4a2fb87e1c7def5"
