name = "MaLiLib"
filename = "malilib-fabric-1.17.1-0.10.0-dev.23.jar"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3379/260/malilib-fabric-1.17.1-0.10.0-dev.23.jar"
hash-format = "sha256"
hash = "8a8a1371fb47b5891c16cd044d8d2e4fd40d9bca9766a86c6d172dfbaf5fd46e"
