name = "MaLiLib"
filename = "malilib-fabric-1.17-pre4-0.10.0-dev.22+beta.2.jar"
side = "client"

[download]
url = "https://masa.dy.fi/mcmods/malilib/malilib-fabric-1.17-pre4-0.10.0-dev.22+beta.2.jar"
hash-format = "sha256"
hash = "dbe7a45b884bbee9c44622321a7723083e9f89acd917e506aa0218119a1edb7d"
