name = "MaLiLib"
filename = "malilib-fabric-1.17-snap-20w51a-0.10.0-dev.21+beta.1.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/Queerbric/queerpack/1.17/mods/malilib-fabric-1.17-snap-20w51a-0.10.0-dev.21+beta.1.jar"
hash-format = "sha256"
hash = "0588d3957a75f0323e254990438086664f3be2720065e76755fd2502ebd10758"
