name = "Mechanized Steam Power"
filename = "Mechanized-1.9.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3013/912/Mechanized-1.9.6.jar"
hash-format = "murmur2"
hash = "3589896037"

[update]
[update.curseforge]
file-id = 3013912
project-id = 373653
release-channel = "beta"
