name = "Mo' Structures"
filename = "mostructures-1.0.0+mc.20w48a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3123/159/mostructures-1.0.0+mc.20w48a.jar"
hash-format = "murmur2"
hash = "3526144036"

[update]
[update.curseforge]
file-id = 3123159
project-id = 378266
release-channel = "beta"
