name = "Mod Menu"
filename = "modmenu-1.14.1+build.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3006/143/modmenu-1.14.1+build.26.jar"
hash-format = "murmur2"
hash = "3773018461"

[update]
[update.curseforge]
file-id = 3006143
project-id = 308702
release-channel = "beta"
