name = "Mod Menu"
filename = "modmenu-2.0.0-beta.1+build.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3109/127/modmenu-2.0.0-beta.1+build.2.jar"
hash-format = "murmur2"
hash = "2369141172"

[update]
[update.curseforge]
file-id = 3109127
project-id = 308702
release-channel = "beta"
