name = "Mod Menu"
filename = "modmenu-2.0.0-beta.3.jar"
side = "both"

[download]
url = "https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/2.0.0-beta.3/modmenu-2.0.0-beta.3.jar"
hash-format = "sha256"
hash = "73cd3973e5e017f4fff011d2a6a4a0234643856bb304dc1c3e3ed78736a5ce69"
