name = "Mooblooms"
filename = "mooblooms-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3005/696/mooblooms-1.3.1.jar"
hash-format = "murmur2"
hash = "3672533326"

[update]
[update.curseforge]
file-id = 3005696
project-id = 333946
release-channel = "beta"
