name = "Name Pain"
filename = "NamePain-1.16.x-Fabric-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2991/311/NamePain-1.16.x-Fabric-1.2.3.jar"
hash-format = "murmur2"
hash = "2272196501"

[update]
[update.curseforge]
file-id = 2991311
project-id = 366263
release-channel = "beta"
