name = "Netherite Plus"
filename = "netherite-plus-mod-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3002/457/netherite-plus-mod-1.1.0.jar"
hash-format = "murmur2"
hash = "551420340"

[update]
[update.curseforge]
file-id = 3002457
project-id = 394120
release-channel = "beta"
