name = "On Soul Fire"
filename = "onsoulfire-r4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3018/564/onsoulfire-r4.jar"
hash-format = "murmur2"
hash = "1486657393"

[update]
[update.curseforge]
file-id = 3018564
project-id = 394667
release-channel = "beta"
