name = "On Soul Fire"
filename = "onsoulfire-r1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3000/790/onsoulfire-r1.jar"
hash-format = "murmur2"
hash = "4076842525"

[update]
[update.curseforge]
file-id = 3000790
project-id = 394667
release-channel = "beta"
