name = "On Soul Fire"
filename = "onsoulfire-r3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3004/142/onsoulfire-r3.jar"
hash-format = "murmur2"
hash = "44138237"

[update]
[update.curseforge]
file-id = 3004142
project-id = 394667
release-channel = "beta"
