name = "Patchouli (Fabric)"
filename = "Patchouli-1.16-38-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2998/202/Patchouli-1.16-38-FABRIC.jar"
hash-format = "murmur2"
hash = "894912339"

[update]
[update.curseforge]
file-id = 2998202
project-id = 393236
release-channel = "beta"
