name = "Pocket Tools"
filename = "pockettools-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3126/311/pockettools-1.1.1.jar"
hash-format = "murmur2"
hash = "1085775039"

[update]
[update.curseforge]
file-id = 3126311
project-id = 418582
release-channel = "beta"
