name = "Pocket Tools"
filename = "pockettools-1.1.2.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3129/82/pockettools-1.1.2.jar"
hash-format = "murmur2"
hash = "579696265"

[update]
[update.curseforge]
file-id = 3129082
project-id = 418582
release-channel = "beta"
