name = "Roughly Enough Items (REI)"
filename = "RoughlyEnoughItems-4.10.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3013/302/RoughlyEnoughItems-4.10.3.jar"
hash-format = "murmur2"
hash = "608292998"

[update]
[update.curseforge]
file-id = 3013302
project-id = 310111
release-channel = "beta"

[option]
optional = true
description = "This is a mod to view items and recipes in Minecraft"
