name = "Roughly Enough Resources"
filename = "rer-2.0.2.jar"
side = "client"

[option]
optional = true
description = "Worldgen support for Roughly Enough Items* (requires REI)"
default = false

[download]
url = "https://edge.forgecdn.net/files/3001/707/rer-2.0.2.jar"
hash-format = "murmur2"
hash = "178523958"

[update]
[update.curseforge]
file-id = 3001707
project-id = 325625
release-channel = "beta"
