name = "Secret Rooms Fabric"
filename = "secretrooms-0.9.1+1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2987/686/secretrooms-0.9.1+1.16.1.jar"
hash-format = "murmur2"
hash = "3420140131"

[update]
[update.curseforge]
file-id = 2987686
project-id = 359248
release-channel = "beta"
