name = "'Slight' Gui Modifications"
filename = "slight-gui-modifications-1.2.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3006/298/slight-gui-modifications-1.2.0.jar"
hash-format = "murmur2"
hash = "3635247939"

[update]
[update.curseforge]
file-id = 3006298
project-id = 380393
release-channel = "beta"

[option]
optional = false
description = "Allows 'slight' gui modifications"
