name = "slotlink"
filename = "slotlink-1.0.3+minecraft-1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3021/540/slotlink-1.0.3+minecraft-1.16.1.jar"
hash-format = "murmur2"
hash = "664013515"

[update]
[update.curseforge]
file-id = 3021540
project-id = 391014
release-channel = "beta"
