name = "Snowy Leaves"
filename = "snowy-leaves-1.16.1-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2997/369/snowy-leaves-1.16.1-1.3.1.jar"
hash-format = "murmur2"
hash = "3830552411"

[update]
[update.curseforge]
file-id = 2997369
project-id = 378676
release-channel = "beta"
