name = "Sodium"
filename = "RoughlyEnoughItems-6.0.0-unstable-20201213.jar"
side = "client"

[download]
url = "https://github.com/mrmangohands/sodium-fabric/releases/download/20w45a-port-0.1.1-SNAPSHOT-2020-11-06/sodium-20w45a-port-fabric-0.1.1-SNAPSHOT-2020-11-06.jar"
hash-format = "sha256"
hash = "6a7a1fae8db9b51a5a6f934d80e8f37afa4a7b3cb0661ae7455c9cd51e4cb9c1"

[option]
optional = true
description = ""
