name = "Sodium"
filename = "sodium-fabric-mc1.16.1-0.1.0.jar"
side = "client"

[option]
optional = true
description = "A Minecraft mod designed to improve frame rates and reduce micro-stutter(incompatible with Canvas Renderer)"
default = false

[download]
url = "https://edge.forgecdn.net/files/3003/93/sodium-fabric-mc1.16.1-0.1.0.jar"
hash-format = "murmur2"
hash = "1872737940"

[update]
[update.curseforge]
file-id = 3003093
project-id = 394468
release-channel = "beta"
