name = "Squake"
filename = "squake.jar"
side = "both"

[download]
url = "squake.jar"
hash-format = "sha256"
hash = "1d97fb66780afba103c7d4e638433c22c98dc6f85dd52829639ed9f2a2a3ecaa"

[option]
optional = true
description = "Quake movement mod for Minecraft"
