name = "Tech Reborn"
filename = "TechReborn-1.16-3.4.5+build.88.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3014/350/TechReborn-1.16-3.4.5+build.88.jar"
hash-format = "murmur2"
hash = "1003120105"

[update]
[update.curseforge]
file-id = 3014350
project-id = 233564
release-channel = "beta"
