name = "Traverse"
filename = "traverse-2.2.12+build.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2992/198/traverse-2.2.12+build.24.jar"
hash-format = "murmur2"
hash = "3933162017"

[update]
[update.curseforge]
file-id = 2992198
project-id = 308777
release-channel = "beta"
