name = "Traverse"
filename = "traverse-2.2.14+build.28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3010/394/traverse-2.2.14+build.28.jar"
hash-format = "murmur2"
hash = "1836252130"

[update]
[update.curseforge]
file-id = 3010394
project-id = 308777
release-channel = "beta"
