name = "Traverse"
filename = "traverse-2.2.13+build.27.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3003/369/traverse-2.2.13+build.27.jar"
hash-format = "murmur2"
hash = "400278771"

[update]
[update.curseforge]
file-id = 3003369
project-id = 308777
release-channel = "beta"
