name = "Trinkets (Fabric)"
filename = "trinkets-2.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3003/416/trinkets-2.6.3.jar"
hash-format = "murmur2"
hash = "3789277238"

[update]
[update.curseforge]
file-id = 3003416
project-id = 341284
release-channel = "beta"
