name = "Unbad Redstone"
filename = "unbad-redstone-1.16-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/587/unbad-redstone-1.16-1.0.0.jar"
hash-format = "murmur2"
hash = "1430464086"

[update]
[update.curseforge]
file-id = 2986587
project-id = 390808
release-channel = "beta"
