name = "The Veggie Way [FABRIC]"
filename = "TheVeggieWay_Fabric-1.17.1-1.1.12.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3379/330/TheVeggieWay_Fabric-1.17.1-1.1.12.jar"
hash-format = "sha256"
hash = "e400d1127b19fc347080439e1efe3c2bf799435e58f94313e1a30ec4a47f48fb"

[update]
[update.curseforge]
file-id = 3118738
project-id = 380345
release-channel = "beta"
