name = "Window Title Changer"
filename = "window_title_changer-2.0.0-1.16.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2988/217/window_title_changer-2.0.0-1.16.1.jar"
hash-format = "murmur2"
hash = "2678235235"

[update]
[update.curseforge]
file-id = 2988217
project-id = 359527
release-channel = "beta"
