name = "Xaero's Minimap"
filename = "Xaeros_Minimap_20.15.3_Fabric_1.16.1.jar"
side = "client"

[option]
optional = true
description = "Displays the nearby world terrain, players, mobs, entities in the corner of your screen. Works as a separate mod but is a lot better with Xaero's World Map"
default = false

[download]
url = "https://edge.forgecdn.net/files/2996/214/Xaeros_Minimap_20.15.3_Fabric_1.16.1.jar"
hash-format = "murmur2"
hash = "2739049403"

[update]
[update.curseforge]
file-id = 2996214
project-id = 263420
release-channel = "beta"
